### ISSUE TITLE
Undeclared Identifer prevents make

### ISSUE THREAD

**Issue by omphalobear** [jgans/thermonucleotideBLAST#5]
**Bug?**
Make fails due to undeclared identifiers: VERSION_MAJOR and VERSION_MINOR

**Platform Tested**
My mac laptop 

**Affected Files**
options.h
options.cpp

**Error messages during make**
options.cpp:437:41: error: use of undeclared identifier 'VERSION_MAJOR'
                cerr << "thermonucleotideBLAST v." << VERSION_MAJOR 
                                                     
options.cpp:438:14: error: use of undeclared identifier 'VERSION_MINOR'
                        << '.' << VERSION_MINOR << endl;

**Temporary solution**
Make succeeds if lines 437 and 438 are commented out in options.cpp

**Comment by jgans** [comment]
Thanks! I forget to upload those files after making changes. Should work now.


Regards,


Jason


________________________________
