### ISSUE TITLE
How to point to BLAST v5 DB

### ISSUE THREAD

**Issue by maxhargrea** [jgans/thermonucleotideBLAST#7]
Hi,

I have downloaded the NCBI BLAST+ nt database from ftp.ncbi.nlm.nih.gov/blast/db and extracted its component archives. What do I need to do on the command line to get tntblast to accept this database? The nt database does not have a fasta, gbk, ptt, or embl format file.

Thanks,

Max.

**Comment by jgans** [comment]
To search a file of assay oligos against an NCBI BLAST+ database (i.e. 'nt'), specify the name of the BLAST+ database as the argument to the`-d` flag. For example, if the BLAST+ nt database has been stored in the directory `/home/blast/`, you could search it using:
```
tntblast -i query.txt -d /home/blast/nt -e 45
```
where `query.txt` is an ASCII text file of PCR primer pairs, `45` is the minimum PCR primer-template melting temperature, `/home/blast` is the database filesystem location and `nt` is the database name (which appears as the prefix of all of the BLAST+ database files in `/home/blast`).

**Comment by maxhargrea** [comment]
Ah, same way you do with BLAST, should have figured. 

Thanks!

Max.
