### ISSUE TITLE
Builds with OpenMP but without MPI always report 1 thread to stdout even when OMP_NUM_THREADS > 1

### ISSUE THREAD

**Issue by dskola** [jgans/thermonucleotideBLAST#8]
Executing `tntblast` built with OpenMP but no MPI always gives:
`Running on local machine [1 thread(s)]` for the first line of output, no matter what the value of OMP_NUM_THREADS.

It appears that only 1 thread is active when printing the usage message so the call to `omp_get_num_threads()` returns 1.
https://github.com/jgans/thermonucleotideBLAST/blob/c5fd6b533cfe1dba332985d30127d08045b01b0f/tntblast.cpp#L94
Shouldn't this be a call to `omp_get_max_threads()` instead as when MPI is included?
https://github.com/jgans/thermonucleotideBLAST/blob/56f83c30f7a126fac062e4e6810b5ecd2b15b041/tntblast.cpp#L75

Changing the call in line 94 to `omp_get_max_threads()` causes the number of threads specified in OMP_NUM_THREADS to be correctly reported.

**Comment by jgans** [comment]
You are correct -- thanks for pointing this out! I have updated the code to use `omp_get_max_threads()`.
